apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://emberstack.github.io/helm-charts
    name: reflector
    # https://artifacthub.io/packages/helm/emberstack/reflector
    version: 9.1.20
    releaseName: reflector
    namespace: reflector
